/*----------------------------------
 *Title:UI自动化组件生成代码生成工具
 *Date:2026/1/3 18:29:40
 *Description:变量需要以[Text]括号加组件类型的格式进行声明,然后右键窗口物体——一键生成UI数据组件脚本即可
 *注意:自动生成的内容仅追加/移除，不会覆盖手写逻辑；新增/删除组件后再次生成，会标记对应代码行
----------------------------------*/
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

namespace KNXL.AutoGenerated.UI
{

	public class GameUIPanel : BasePanel
	{
		//字段声明
		public TextMeshProUGUI tmpTime;
		public TextMeshProUGUI tmpStep;
		public Button btnInfo;
		public Button btnMute;
		public Button btnHome;
		// 留给新增的字段
		public TextMeshProUGUI LevelInfo;
		//自己手写的字段声明，不会被覆盖

		//重写Awake方法
		protected override void Awake()
		{
			base.Awake();
			//自己手写的Awake逻辑，不会被覆盖
		}

		//重写Start方法,完成事件绑定
		protected override void Start()
		{
			base.Start();
			//组件事件绑定
			btnInfo.onClick.AddListener(() => OnbtnInfoButtonClick());
			btnMute.onClick.AddListener(() => OnbtnMuteButtonClick());
			btnHome.onClick.AddListener(() => OnbtnHomeButtonClick());
			// 留给新增的组件事件绑定



			//自己手写的Start逻辑，不会被覆盖
		}

		void OnEnable()
		{
			// 绑定游戏逻辑中的时间更新事件
			EventCenter.Instance.AddEventListener<int>(E_EventType.E_TimeUpdate, OnTimeUpdate);
			// 绑定游戏逻辑中的步数更新事件
			EventCenter.Instance.AddEventListener<int>(E_EventType.E_StepUpdate, OnStepUpdate);
		}

		void OnDisable()
		{
			// 解绑游戏逻辑中的时间更新事件
			EventCenter.Instance.RemoveEventListener<int>(E_EventType.E_TimeUpdate, OnTimeUpdate);
			// 解绑游戏逻辑中的步数更新事件
			EventCenter.Instance.RemoveEventListener<int>(E_EventType.E_StepUpdate, OnStepUpdate);
		}

		public override void ShowMe(UnityAction callback = null)
		{
			//执行父类的ShowMe方法
			base.ShowMe(callback);
			//自己手写的ShowMe逻辑，不会被覆盖
		}

		public override void HideMe(UnityAction callback = null)
		{
			//执行父类的HideMe方法
			base.HideMe(callback);
			//自己手写的HideMe逻辑，不会被覆盖
		}

		private void OnbtnInfoButtonClick()
		{

		}

		private void OnbtnMuteButtonClick()
		{

		}

		private void OnbtnHomeButtonClick()
		{

		}

		// 留给新增的组件事件绑定函数

		//自己写的内容
		private void OnTimeUpdate(int time)
		{
			tmpTime.text = time.ToString() + "s";
		}

		private void OnStepUpdate(int step)
		{
			tmpStep.text = step.ToString();
		}

		/// <summary>
		/// 更新游戏UI中的等级信息
		/// </summary>
		/// <param name="row">当前等级的行数</param>
		/// <param name="col">当前等级的列数</param>
		public void UpdateLevelInfo(int row, int col)
		{
			LevelInfo.text = $"{row}X{col}";
		}
	}
}