/*----------------------------------
 *Title:UI自动化组件生成代码生成工具
 *Date:2026/1/3 18:29:47
 *Description:变量需要以[Text]括号加组件类型的格式进行声明,然后右键窗口物体——一键生成UI数据组件脚本即可
 *注意:自动生成的内容仅追加/移除，不会覆盖手写逻辑；新增/删除组件后再次生成，会标记对应代码行
----------------------------------*/
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

namespace KNXL.AutoGenerated.UI
{

	public class LevelPassPanel : BasePanel
	{
		//字段声明
		public TextMeshProUGUI tmpTime;
		public TextMeshProUGUI tmpStep;
		public TextMeshProUGUI tmpLevelIndex;
		public Button btnRestart;
		public Button btnNext;
		// 留给新增的字段
		//自己手写的字段声明，不会被覆盖

		//重写Awake方法
		protected override void Awake()
		{
			base.Awake();
			//自己手写的Awake逻辑，不会被覆盖
		}

		//重写Start方法,完成事件绑定
		protected override void Start()
		{
			base.Start();
			//组件事件绑定
			btnRestart.onClick.AddListener(() => OnbtnRestartButtonClick());
			btnNext.onClick.AddListener(() => OnbtnNextButtonClick());
			// 留给新增的组件事件绑定
			//自己手写的Start逻辑，不会被覆盖
		}

		public override void ShowMe(UnityAction callback = null)
		{
			//执行父类的ShowMe方法
			base.ShowMe(callback);
			//自己手写的ShowMe逻辑，不会被覆盖
		}

		public override void HideMe(UnityAction callback = null)
		{
			//执行父类的HideMe方法
			base.HideMe(callback);
			//自己手写的HideMe逻辑，不会被覆盖
		}

		private void OnbtnRestartButtonClick()
		{

		}

		private void OnbtnNextButtonClick()
		{
			UIMgr.Instance.HidePanel<LevelPassPanel>(hideAnimType: E_HideAnimType.FadeOut, callBack: () =>
			{
				GameManager.Instance.GoToNextLevel();

			});
		}

		// 留给新增的组件事件绑定函数
		//自己写的内容
		public void UpdateLevelPassInfo(int time, int step, int levelIndex)
		{
			tmpTime.text = "Times: " + time.ToString();
			tmpStep.text = "Move Counts: " + step.ToString();
			tmpLevelIndex.text = "Level: " + levelIndex.ToString();
		}
	}
}