using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.UI;

// using KNXL.AutoGenerated.UI;
using UnityEngine;

public class Main : MonoBehaviour
{
    // Start is called before the first frame update
    void Awake()
    {
        GameManager.Instance.LoadConfig();
        UIMgr.Instance.ShowPanel<GameStartPanel>();
    }


}
