using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 配置数据基类（所有配置表类的父类）
    /// </summary>
    public abstract class BaseConfig
    {
        /// <summary>
        /// 主键值（子类必须实现）
        /// </summary>
        public abstract object PrimaryKey { get; }

        /// <summary>
        /// 数据合法性校验
        /// </summary>
        /// <returns>是否合法</returns>
        public virtual bool Validate() => true;
    }
}