using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Networking;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 全局配置管理器（单例）
    /// </summary>
    public class ConfigManager
    {
        #region 单例
        private static ConfigManager _instance;
        public static ConfigManager Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new ConfigManager();
                }
                return _instance;
            }
        }
        #endregion

        // 新增：配置清单
        private ConfigManifest _configManifest;

        /// <summary>
        /// 配置表字典（Key=表名，Value=表实例）
        /// </summary>
        private Dictionary<string, IConfigTable> _configTables = new Dictionary<string, IConfigTable>();

        /// <summary>
        /// JSON根路径类型
        /// </summary>
        private ConfigPathType _pathType = ConfigPathType.StreamingAssets;

        /// <summary>
        /// JSON子路径
        /// </summary>
        private string _subPath = "Config";

        /// <summary>
        /// 加载模式
        /// </summary>
        private ConfigLoadMode _loadMode = ConfigLoadMode.PreloadAll;

        /// <summary>
        /// 是否初始化完成
        /// </summary>
        public bool IsInitialized { get; private set; }

        /// <summary>
        /// 已加载的表数量
        /// </summary>
        public int TableCount => _configTables.Count;

        /// <summary>
        /// 设置JSON文件路径
        /// </summary>
        /// <param name="pathType">路径类型</param>
        /// <param name="subPath">子路径</param>
        public void SetJsonRootPath(ConfigPathType pathType, string subPath = "Config")
        {
            _pathType = pathType;
            _subPath = subPath;
        }

        /// <summary>
        /// 设置加载模式
        /// </summary>
        /// <param name="loadMode">加载模式</param>
        public void SetLoadMode(ConfigLoadMode loadMode)
        {
            _loadMode = loadMode;
        }

        /// <summary>
        /// 从清单文件初始化（核心新增：自动加载所有表）
        /// </summary>
        /// <returns>协程</returns>
        public IEnumerator InitFromManifest()
        {
            if (IsInitialized)
            {
                ConfigHelper.LogInfo("ConfigManager", "已初始化，无需重复执行");
                yield break;
            }

            // 1. 读取配置清单
            string manifestPath = ConfigHelper.GetJsonPath("config_manifest", _pathType, _subPath);
            string manifestJson = ConfigHelper.ReadJsonFile(manifestPath, _pathType);
            if (string.IsNullOrEmpty(manifestJson))
            {
                ConfigHelper.LogError("ConfigManager", "读取配置清单失败");
                yield break;
            }

            // 2. 反序列化清单
            _configManifest = JsonConvert.DeserializeObject<ConfigManifest>(manifestJson);
            if (_configManifest == null || _configManifest.tables == null || _configManifest.tables.Count == 0)
            {
                ConfigHelper.LogError("ConfigManager", "配置清单为空或格式错误");
                yield break;
            }

            ConfigHelper.LogInfo("ConfigManager", $"读取配置清单成功，共{_configManifest.table_count}张表");

            // 3. 遍历清单自动加载所有表
            foreach (var tableMeta in _configManifest.tables)
            {
                yield return MonoMgr.Instance.StartCoroutine(LoadTableFromMeta(tableMeta));
                yield return new WaitForEndOfFrame(); // 每加载一张表让出一帧，避免卡顿
            }

            IsInitialized = true;
            ConfigHelper.LogInfo("ConfigManager", $"从清单自动加载完成，成功加载{TableCount}张表");
        }

        /// <summary>
        /// 根据表元信息加载表（反射实现，无需硬编码类型）
        /// </summary>
        /// <param name="tableMeta">表元信息</param>
        /// <returns>协程</returns>
        private IEnumerator LoadTableFromMeta(TableMetaInfo tableMeta)
        {
            IEnumerator loadCoroutine = null;
            Exception loadException = null;

            try
            {
                // 1. 通过反射获取配置类类型（如CfgRole）
                Assembly assembly = Assembly.GetExecutingAssembly();
                Type configType = assembly.GetType($"KNXL.AutoGenerated.Data.{tableMeta.class_name}");
                if (configType == null)
                {
                    ConfigHelper.LogError("ConfigManager", $"未找到配置类：KNXL.AutoGenerated.Data.{tableMeta.class_name}");
                    yield break;
                }

                // 2. 检查是否继承BaseConfig
                if (!typeof(BaseConfig).IsAssignableFrom(configType))
                {
                    ConfigHelper.LogError("ConfigManager", $"{tableMeta.class_name}未继承BaseConfig");
                    yield break;
                }

                // 3. 反射调用LoadTableAsync方法（泛型）
                MethodInfo loadMethod = typeof(ConfigManager).GetMethod("LoadTableAsync", BindingFlags.NonPublic | BindingFlags.Instance)
                    ?.MakeGenericMethod(configType);

                if (loadMethod == null)
                {
                    ConfigHelper.LogError("ConfigManager", "未找到LoadTableAsync方法");
                    yield break;
                }

                // 4. 执行异步加载 - 先获取协程（仅调用方法，不yield）
                loadCoroutine = (IEnumerator)loadMethod.Invoke(this, new object[] { tableMeta.table_name });
            }
            catch (Exception e)
            {
                loadException = e;
                ConfigHelper.LogError("ConfigManager", $"加载表{tableMeta.table_name}失败：{e.Message}");
            }

            // 关键：将yield return移出try/catch块外
            if (loadException != null)
            {
                yield break;
            }
            // 5. 等待异步加载完成
            if (loadCoroutine != null)
            {
                yield return MonoMgr.Instance.StartCoroutine(loadCoroutine);
            }
        }

        /// <summary>
        /// 获取配置清单
        /// </summary>
        /// <returns>配置清单</returns>
        public ConfigManifest GetConfigManifest()
        {
            return _configManifest;
        }

        /// <summary>
        /// 获取表的元信息
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <returns>元信息</returns>
        public TableMetaInfo GetTableMetaInfo(string tableName)
        {
            return _configManifest?.tables?.Find(t => t.table_name.Equals(tableName, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// 加载指定表（同步）
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="tableName">表名</param>
        /// <returns>配置表实例</returns>
        public ConfigTable<T> LoadTable<T>(string tableName) where T : BaseConfig, new()
        {
            // 已加载则返回缓存
            if (_configTables.TryGetValue(tableName, out var existTable))
            {
                return existTable as ConfigTable<T>;
            }

            // 创建表实例
            var table = new ConfigTable<T>(tableName);
            string jsonPath = ConfigHelper.GetJsonPath(tableName, _pathType, _subPath);
            string jsonContent = ConfigHelper.ReadJsonFile(jsonPath, _pathType);

            if (table.LoadFromJson(jsonContent))
            {
                _configTables[tableName] = table;
                return table;
            }
            else
            {
                ConfigHelper.LogError("ConfigManager", $"加载表失败：{tableName}");
                return null;
            }
        }

        /// <summary>
        /// 异步加载指定表
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="tableName">表名</param>
        /// <returns>协程</returns>
        private IEnumerator LoadTableAsync<T>(string tableName) where T : BaseConfig, new()
        {
            if (_configTables.TryGetValue(tableName, out var existTable))
            {
                yield break;
            }

            var table = new ConfigTable<T>(tableName);
            string jsonPath = ConfigHelper.GetJsonPath(tableName, _pathType, _subPath);

            // 异步读取文件（模拟）
            string jsonContent = string.Empty;
            if (_pathType == ConfigPathType.StreamingAssets && Application.platform == RuntimePlatform.Android)
            {
                using (UnityWebRequest req = UnityWebRequest.Get(jsonPath))
                {
                    yield return req.SendWebRequest();
                    if (!string.IsNullOrEmpty(req.error))
                    {
                        ConfigHelper.LogError("ConfigManager", $"异步读取失败：{req.error}");
                        yield break;
                    }
                    jsonContent = req.downloadHandler.text;
                }
            }
            else
            {
                // 非Android平台同步读取（实际可封装真正的异步文件读取）
                yield return new WaitForEndOfFrame();
                jsonContent = ConfigHelper.ReadJsonFile(jsonPath, _pathType);
            }

            if (table.LoadFromJson(jsonContent))
            {
                _configTables[tableName] = table;
            }
            else
            {
                ConfigHelper.LogError("ConfigManager", $"异步加载表失败：{tableName}");
            }
        }

        /// <summary>
        /// 重新加载指定表（热更）
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <returns>是否成功</returns>
        public bool ReloadTable(string tableName)
        {
            if (!_configTables.ContainsKey(tableName))
            {
                ConfigHelper.LogWarning("ConfigManager", $"表未加载：{tableName}");
                return false;
            }

            // 清空原有数据
            _configTables[tableName].Clear();
            _configTables.Remove(tableName);

            // 重新加载
            // 注意：这里需要根据表名反射创建对应类型，或维护表名-类型映射表
            // 示例简化处理，实际项目需扩展
            ConfigHelper.LogInfo("ConfigManager", $"重新加载表：{tableName}");
            return true;
        }

        /// <summary>
        /// 获取已加载的表
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <returns>配置表实例</returns>
        public ConfigTable<T> GetTable<T>() where T : BaseConfig, new()
        {
            // 获取泛型类型对应的表名（移除Cfg前缀）
            string typeName = typeof(T).Name;
            string tableName = typeName.StartsWith("Cfg") ? typeName.Substring(3) : typeName;

            // 懒加载模式：未加载则自动加载
            if (_loadMode == ConfigLoadMode.LazyLoad && !_configTables.ContainsKey(tableName))
            {
                return LoadTable<T>(tableName);
            }

            _configTables.TryGetValue(tableName, out var table);
            return table as ConfigTable<T>;
        }

        /// <summary>
        /// 按主键获取单条配置
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="primaryKey">主键值</param>
        /// <returns>配置数据</returns>
        public T GetData<T>(object primaryKey) where T : BaseConfig, new()
        {
            var table = GetTable<T>();
            return table?.GetData(primaryKey);
        }

        /// <summary>
        /// 安全获取单条配置
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="primaryKey">主键值</param>
        /// <param name="data">输出数据</param>
        /// <returns>是否获取成功</returns>
        public bool TryGetData<T>(object primaryKey, out T data) where T : BaseConfig, new()
        {
            data = default;
            var table = GetTable<T>();
            if (table == null) return false;

            return table.TryGetData(primaryKey, out data);
        }

        /// <summary>
        /// 获取表的所有数据
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <returns>数据列表</returns>
        public List<T> GetAllData<T>() where T : BaseConfig, new()
        {
            var table = GetTable<T>();
            return table?.AllData as List<T> ?? new List<T>();
        }

        /// <summary>
        /// 按条件查询数据
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="condition">过滤条件</param>
        /// <returns>符合条件的数据列表</returns>
        public List<T> GetDataByCondition<T>(Func<T, bool> condition) where T : BaseConfig, new()
        {
            var table = GetTable<T>();
            return table?.FindAll(condition) ?? new List<T>();
        }

        /// <summary>
        /// 卸载指定表
        /// </summary>
        /// <param name="tableName">表名</param>
        public void UnloadTable(string tableName)
        {
            if (_configTables.TryGetValue(tableName, out var table))
            {
                table.Clear();
                _configTables.Remove(tableName);
                ConfigHelper.LogInfo("ConfigManager", $"卸载表：{tableName}");
            }
        }

        /// <summary>
        /// 清空所有表
        /// </summary>
        public void ClearAll()
        {
            foreach (var table in _configTables.Values)
            {
                table.Clear();
            }
            _configTables.Clear();
            IsInitialized = false;
            ConfigHelper.LogInfo("ConfigManager", "清空所有配置表");
        }
    }
}