using System;
using System.IO;
using UnityEngine;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 配置工具类（路径、日志、文件读取）
    /// </summary>
    public static class ConfigHelper
    {
        /// <summary>
        /// 获取JSON文件路径
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <param name="pathType">路径类型</param>
        /// <param name="subPath">子路径</param>
        /// <returns>完整路径</returns>
        public static string GetJsonPath(string tableName, ConfigPathType pathType, string subPath = "Config")
        {
            string rootPath = string.Empty;
            switch (pathType)
            {
                case ConfigPathType.StreamingAssets:
                    rootPath = Application.streamingAssetsPath;
                    break;
                case ConfigPathType.Resources:
                    rootPath = Application.dataPath + "/Resources";
                    break;
                case ConfigPathType.PersistentDataPath:
                    rootPath = Application.persistentDataPath;
                    break;
            }

            string fullPath = Path.Combine(rootPath, subPath, $"{tableName}.json");
            return fullPath.Replace("\\", "/");
        }

        /// <summary>
        /// 读取JSON文件内容
        /// </summary>
        /// <param name="path">文件路径</param>
        /// <param name="pathType">路径类型</param>
        /// <returns>JSON内容</returns>
        public static string ReadJsonFile(string path, ConfigPathType pathType = ConfigPathType.StreamingAssets)
        {
            try
            {
                if (pathType == ConfigPathType.Resources)
                {
                    // Resources加载（无需后缀）
                    string resPath = path.Replace(Application.dataPath + "/Resources/", "")
                                         .Replace(".json", "");
                    var textAsset = Resources.Load<TextAsset>(resPath);
                    if (textAsset == null)
                    {
                        LogError("ConfigHelper", $"Resources中未找到配置文件：{resPath}");
                        return string.Empty;
                    }
                    return textAsset.text;
                }
                else
                {
                    // 普通文件读取
                    if (!File.Exists(path))
                    {
                        LogError("ConfigHelper", $"配置文件不存在：{path}");
                        return string.Empty;
                    }

                    // StreamingAssets在Android下需要用WWW读取
                    if (pathType == ConfigPathType.StreamingAssets && Application.platform == RuntimePlatform.Android)
                    {
                        using (var www = new WWW(path))
                        {
                            while (!www.isDone) { }
                            if (!string.IsNullOrEmpty(www.error))
                            {
                                LogError("ConfigHelper", $"读取Android配置文件失败：{www.error}");
                                return string.Empty;
                            }
                            return www.text;
                        }
                    }
                    else
                    {
                        return File.ReadAllText(path, System.Text.Encoding.UTF8);
                    }
                }
            }
            catch (Exception e)
            {
                LogError("ConfigHelper", $"读取JSON失败：{e.Message}");
                return string.Empty;
            }
        }

        #region 日志封装
        public static void LogInfo(string tableName, string msg)
        {
            Debug.Log($"[Config][{tableName}] {msg}");
        }

        public static void LogWarning(string tableName, string msg)
        {
            Debug.LogWarning($"[Config][{tableName}] {msg}");
        }

        public static void LogError(string tableName, string msg)
        {
            Debug.LogError($"[Config][{tableName}] {msg}");
        }
        #endregion
    }
}