using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 泛型配置表（单张表的封装）
    /// </summary>
    /// <typeparam name="T">配置数据类型</typeparam>
    public class ConfigTable<T> : IConfigTable where T : BaseConfig, new()
    {
        /// <summary>
        /// 主键索引字典（快速查询）
        /// </summary>
        private Dictionary<object, T> _dataDict = new Dictionary<object, T>();

        /// <summary>
        /// 所有数据列表（遍历用）
        /// </summary>
        private List<T> _allData = new List<T>();

        /// <summary>
        /// 主键字段名（默认id）
        /// </summary>
        private string _primaryKeyName = "id";

        /// <summary>
        /// 表名
        /// </summary>
        public string TableName { get; private set; }

        /// <summary>
        /// 数据行数
        /// </summary>
        public int Count => _allData.Count;

        /// <summary>
        /// 只读所有数据（防止外部修改）
        /// </summary>
        public IReadOnlyList<T> AllData => _allData.AsReadOnly();

        public ConfigTable(string tableName, string primaryKeyName = "id")
        {
            TableName = tableName;
            _primaryKeyName = primaryKeyName;
        }

        /// <summary>
        /// 从JSON加载数据
        /// </summary>
        public bool LoadFromJson(string jsonContent)
        {
            try
            {
                Clear();
                
                // 反序列化JSON
                var dataList = JsonConvert.DeserializeObject<List<T>>(jsonContent);
                if (dataList == null || dataList.Count == 0)
                {
                    ConfigHelper.LogError(TableName, "JSON数据为空");
                    return false;
                }

                // 构建主键索引 + 数据校验
                foreach (var data in dataList)
                {
                    if (!data.Validate())
                    {
                        ConfigHelper.LogWarning(TableName, $"数据校验失败，跳过该条数据：{data.PrimaryKey}");
                        continue;
                    }

                    var key = data.PrimaryKey;
                    if (key == null)
                    {
                        ConfigHelper.LogWarning(TableName, "主键为空，跳过该条数据");
                        continue;
                    }

                    if (!_dataDict.ContainsKey(key))
                    {
                        _dataDict.Add(key, data);
                        _allData.Add(data);
                    }
                    else
                    {
                        ConfigHelper.LogWarning(TableName, $"主键重复：{key}，跳过该条数据");
                    }
                }

                ConfigHelper.LogInfo(TableName, $"加载成功，有效数据行数：{Count}");
                return true;
            }
            catch (Exception e)
            {
                ConfigHelper.LogError(TableName, $"加载失败：{e.Message}");
                return false;
            }
        }

        /// <summary>
        /// 按主键查询数据
        /// </summary>
        /// <param name="primaryKey">主键值</param>
        /// <returns>配置数据（不存在返回null）</returns>
        public T GetData(object primaryKey)
        {
            _dataDict.TryGetValue(primaryKey, out var data);
            return data;
        }

        /// <summary>
        /// 安全查询数据
        /// </summary>
        /// <param name="primaryKey">主键值</param>
        /// <param name="data">输出数据</param>
        /// <returns>是否查询成功</returns>
        public bool TryGetData(object primaryKey, out T data)
        {
            return _dataDict.TryGetValue(primaryKey, out data);
        }

        /// <summary>
        /// 按条件查询第一条数据
        /// </summary>
        /// <param name="condition">过滤条件</param>
        /// <returns>符合条件的第一条数据</returns>
        public T FindFirst(Func<T, bool> condition)
        {
            return _allData.FirstOrDefault(condition);
        }

        /// <summary>
        /// 按条件过滤数据
        /// </summary>
        /// <param name="condition">过滤条件</param>
        /// <returns>符合条件的数据列表</returns>
        public List<T> FindAll(Func<T, bool> condition)
        {
            return _allData.Where(condition).ToList();
        }

        /// <summary>
        /// 清空数据
        /// </summary>
        public void Clear()
        {
            _dataDict.Clear();
            _allData.Clear();
        }
    }
}