using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 全局配置管理器（单例）
    /// </summary>
    public class ConfigManager
    {
        #region 单例
        private static ConfigManager _instance;
        public static ConfigManager Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new ConfigManager();
                }
                return _instance;
            }
        }
        #endregion

        /// <summary>
        /// 配置表字典（Key=表名，Value=表实例）
        /// </summary>
        private Dictionary<string, IConfigTable> _configTables = new Dictionary<string, IConfigTable>();

        /// <summary>
        /// JSON根路径类型
        /// </summary>
        private ConfigPathType _pathType = ConfigPathType.StreamingAssets;

        /// <summary>
        /// JSON子路径
        /// </summary>
        private string _subPath = "Config";

        /// <summary>
        /// 加载模式
        /// </summary>
        private ConfigLoadMode _loadMode = ConfigLoadMode.PreloadAll;

        /// <summary>
        /// 是否初始化完成
        /// </summary>
        public bool IsInitialized { get; private set; }

        /// <summary>
        /// 已加载的表数量
        /// </summary>
        public int TableCount => _configTables.Count;

        /// <summary>
        /// 设置JSON文件路径
        /// </summary>
        /// <param name="pathType">路径类型</param>
        /// <param name="subPath">子路径</param>
        public void SetJsonRootPath(ConfigPathType pathType, string subPath = "Config")
        {
            _pathType = pathType;
            _subPath = subPath;
        }

        /// <summary>
        /// 设置加载模式
        /// </summary>
        /// <param name="loadMode">加载模式</param>
        public void SetLoadMode(ConfigLoadMode loadMode)
        {
            _loadMode = loadMode;
        }

        /// <summary>
        /// 同步初始化（预加载所有表）
        /// </summary>
        public void Init()
        {
            if (IsInitialized)
            {
                ConfigHelper.LogInfo("ConfigManager", "已初始化，无需重复执行");
                return;
            }

            // 预加载所有表（需自定义实现：遍历指定目录下的所有JSON文件）
            // 这里示例仅加载已知表名，实际项目可通过反射/配置清单获取所有表名
            var tableNames = new List<string> { "Role", "Skill", "Item" };
            // foreach (var tableName in tableNames)
            // {
            //     LoadTable(tableName);
            // }

            IsInitialized = true;
            ConfigHelper.LogInfo("ConfigManager", "初始化完成，表数量：" + TableCount);
        }

        /// <summary>
        /// 异步初始化（Unity协程）
        /// </summary>
        public IEnumerator InitAsync()
        {
            if (IsInitialized)
            {
                ConfigHelper.LogInfo("ConfigManager", "已初始化，无需重复执行");
                yield break;
            }

            var tableNames = new List<string> { "Role", "Skill", "Item" };
            // foreach (var tableName in tableNames)
            // {
            //     yield return StartCoroutine(LoadTableAsync(tableName));
            //     yield return new WaitForEndOfFrame(); // 每加载一张表，让出一帧
            // }

            IsInitialized = true;
            ConfigHelper.LogInfo("ConfigManager", "异步初始化完成，表数量：" + TableCount);
        }

        /// <summary>
        /// 加载指定表（同步）
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="tableName">表名</param>
        /// <returns>配置表实例</returns>
        public ConfigTable<T> LoadTable<T>(string tableName) where T : BaseConfig, new()
        {
            // 已加载则返回缓存
            if (_configTables.TryGetValue(tableName, out var existTable))
            {
                return existTable as ConfigTable<T>;
            }

            // 创建表实例
            var table = new ConfigTable<T>(tableName);
            string jsonPath = ConfigHelper.GetJsonPath(tableName, _pathType, _subPath);
            string jsonContent = ConfigHelper.ReadJsonFile(jsonPath, _pathType);

            if (table.LoadFromJson(jsonContent))
            {
                _configTables[tableName] = table;
                return table;
            }
            else
            {
                ConfigHelper.LogError("ConfigManager", $"加载表失败：{tableName}");
                return null;
            }
        }

        /// <summary>
        /// 异步加载指定表
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="tableName">表名</param>
        /// <returns>协程</returns>
        public IEnumerator LoadTableAsync<T>(string tableName) where T : BaseConfig, new()
        {
            if (_configTables.TryGetValue(tableName, out var existTable))
            {
                yield break;
            }

            var table = new ConfigTable<T>(tableName);
            string jsonPath = ConfigHelper.GetJsonPath(tableName, _pathType, _subPath);

            // 异步读取文件（模拟）
            string jsonContent = string.Empty;
            if (_pathType == ConfigPathType.StreamingAssets && Application.platform == RuntimePlatform.Android)
            {
                using (UnityWebRequest req = UnityWebRequest.Get(jsonPath))
                {
                    yield return req.SendWebRequest();
                    if (!string.IsNullOrEmpty(req.error))
                    {
                        ConfigHelper.LogError("ConfigManager", $"异步读取失败：{req.error}");
                        yield break;
                    }
                    jsonContent = req.downloadHandler.text;
                }
            }
            else
            {
                // 非Android平台同步读取（实际可封装真正的异步文件读取）
                yield return new WaitForEndOfFrame();
                jsonContent = ConfigHelper.ReadJsonFile(jsonPath, _pathType);
            }

            if (table.LoadFromJson(jsonContent))
            {
                _configTables[tableName] = table;
            }
            else
            {
                ConfigHelper.LogError("ConfigManager", $"异步加载表失败：{tableName}");
            }
        }

        /// <summary>
        /// 重新加载指定表（热更）
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <returns>是否成功</returns>
        public bool ReloadTable(string tableName)
        {
            if (!_configTables.ContainsKey(tableName))
            {
                ConfigHelper.LogWarning("ConfigManager", $"表未加载：{tableName}");
                return false;
            }

            // 清空原有数据
            _configTables[tableName].Clear();
            _configTables.Remove(tableName);

            // 重新加载
            // 注意：这里需要根据表名反射创建对应类型，或维护表名-类型映射表
            // 示例简化处理，实际项目需扩展
            ConfigHelper.LogInfo("ConfigManager", $"重新加载表：{tableName}");
            return true;
        }

        /// <summary>
        /// 获取已加载的表
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <returns>配置表实例</returns>
        public ConfigTable<T> GetTable<T>() where T : BaseConfig, new()
        {
            // 获取泛型类型对应的表名（移除Cfg前缀）
            string typeName = typeof(T).Name;
            string tableName = typeName.StartsWith("Cfg") ? typeName.Substring(3) : typeName;

            // 懒加载模式：未加载则自动加载
            if (_loadMode == ConfigLoadMode.LazyLoad && !_configTables.ContainsKey(tableName))
            {
                return LoadTable<T>(tableName);
            }

            _configTables.TryGetValue(tableName, out var table);
            return table as ConfigTable<T>;
        }

        /// <summary>
        /// 按主键获取单条配置
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="primaryKey">主键值</param>
        /// <returns>配置数据</returns>
        public T GetData<T>(object primaryKey) where T : BaseConfig, new()
        {
            var table = GetTable<T>();
            return table?.GetData(primaryKey);
        }

        /// <summary>
        /// 安全获取单条配置
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="primaryKey">主键值</param>
        /// <param name="data">输出数据</param>
        /// <returns>是否获取成功</returns>
        public bool TryGetData<T>(object primaryKey, out T data) where T : BaseConfig, new()
        {
            data = default;
            var table = GetTable<T>();
            if (table == null) return false;

            return table.TryGetData(primaryKey, out data);
        }

        /// <summary>
        /// 获取表的所有数据
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <returns>数据列表</returns>
        public List<T> GetAllData<T>() where T : BaseConfig, new()
        {
            var table = GetTable<T>();
            return table?.AllData as List<T> ?? new List<T>();
        }

        /// <summary>
        /// 按条件查询数据
        /// </summary>
        /// <typeparam name="T">配置数据类型</typeparam>
        /// <param name="condition">过滤条件</param>
        /// <returns>符合条件的数据列表</returns>
        public List<T> GetDataByCondition<T>(Func<T, bool> condition) where T : BaseConfig, new()
        {
            var table = GetTable<T>();
            return table?.FindAll(condition) ?? new List<T>();
        }

        /// <summary>
        /// 卸载指定表
        /// </summary>
        /// <param name="tableName">表名</param>
        public void UnloadTable(string tableName)
        {
            if (_configTables.TryGetValue(tableName, out var table))
            {
                table.Clear();
                _configTables.Remove(tableName);
                ConfigHelper.LogInfo("ConfigManager", $"卸载表：{tableName}");
            }
        }

        /// <summary>
        /// 清空所有表
        /// </summary>
        public void ClearAll()
        {
            foreach (var table in _configTables.Values)
            {
                table.Clear();
            }
            _configTables.Clear();
            IsInitialized = false;
            ConfigHelper.LogInfo("ConfigManager", "清空所有配置表");
        }
    }
}