namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 配置加载模式
    /// </summary>
    public enum ConfigLoadMode
    {
        /// <summary>
        /// 启动时预加载所有表
        /// </summary>
        PreloadAll,

        /// <summary>
        /// 按需加载（首次查询时加载）
        /// </summary>
        LazyLoad,

        /// <summary>
        /// 异步加载
        /// </summary>
        AsyncLoad
    }

    /// <summary>
    /// 配置文件路径类型
    /// </summary>
    public enum ConfigPathType
    {
        /// <summary>
        /// StreamingAssets目录（只读，打包后可访问）
        /// </summary>
        StreamingAssets,

        /// <summary>
        /// Resources目录（只读，可打包到AssetBundle）
        /// </summary>
        Resources,

        /// <summary>
        /// PersistentDataPath目录（可读写，热更用）
        /// </summary>
        PersistentDataPath
    }
}