using System;
using System.Collections.Generic;
using UnityEngine;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 配置清单模型（对应Python生成的config_manifest.json）
    /// </summary>
    [Serializable]
    public class ConfigManifest
    {
        [SerializeField] public string version;
        [SerializeField] public string generate_time;
        [SerializeField] public int table_count;
        [SerializeField] public List<TableMetaInfo> tables;
    }

    /// <summary>
    /// 表元信息
    /// </summary>
    [Serializable]
    public class TableMetaInfo
    {
        [SerializeField] public string table_name;
        [SerializeField] public string class_name;
        [SerializeField] public string json_path;
        [SerializeField] public string primary_key;
        [SerializeField] public int row_count;
        [SerializeField] public List<FieldMetaInfo> fields;
    }

    /// <summary>
    /// 字段元信息
    /// </summary>
    [Serializable]
    public class FieldMetaInfo
    {
        [SerializeField] public string name;
        [SerializeField] public string type;
        [SerializeField] public string desc;
        [SerializeField] public bool is_enum;
    }
}