namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 配置表接口（统一管理所有表）
    /// </summary>
    public interface IConfigTable
    {
        /// <summary>
        /// 表名
        /// </summary>
        string TableName { get; }

        /// <summary>
        /// 数据行数
        /// </summary>
        int Count { get; }

        /// <summary>
        /// 从JSON字符串加载数据
        /// </summary>
        /// <param name="jsonContent">JSON内容</param>
        /// <returns>是否加载成功</returns>
        bool LoadFromJson(string jsonContent);

        /// <summary>
        /// 清空表数据
        /// </summary>
        void Clear();
    }
}