using System;
using System.Collections.Generic;
using UnityEngine;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// EnemyData配置表（自动生成）
    /// </summary>
    [Serializable]
    public class CfgEnemyData : BaseConfig
    {
        /// <summary>
        /// 主键
        /// </summary>
        [SerializeField]
        public int id { get; set; }

        /// <summary>
        /// 血量
        /// </summary>
        [SerializeField]
        public float hp { get; set; }

        /// <summary>
        /// 11
        /// </summary>
        [SerializeField]
        public float moveSpeed { get; set; }

        /// <summary>
        /// 22
        /// </summary>
        [SerializeField]
        public float roundSpeed { get; set; }

        /// <summary>
        /// 33
        /// </summary>
        [SerializeField]
        public bool isLook { get; set; }

        /// <summary>
        /// 44
        /// </summary>
        [SerializeField]
        public string name { get; set; }

        /// <summary>
        /// 55
        /// </summary>
        [SerializeField]
        public string testInt { get; set; }

        /// <summary>
        /// 66
        /// </summary>
        [SerializeField]
        public string testString { get; set; }

        /// <summary>
        /// 77
        /// </summary>
        [SerializeField]
        public string testFloat { get; set; }

        /// <summary>
        /// 88
        /// </summary>
        [SerializeField]
        public E_Type type { get; set; }

        /// <summary>
        /// 主键（id）
        /// </summary>
        public override object PrimaryKey => id;

    /// <summary>
    /// 数据合法性校验（适配Unity）
    /// </summary>
    public override bool Validate()
    {
        // 主键校验
        if (id <= 0)
        {
            ConfigHelper.LogError("CfgEnemyData", $"主键id非法：{id}");
            return false;
        }
        // 主键范围校验
        if (id < 1)
        {
            ConfigHelper.LogError("CfgEnemyData", $"主键id值{id}小于最小值1");
            return false;
        }
        if (id > 99999)
        {
            ConfigHelper.LogError("CfgEnemyData", $"主键id值{id}大于最大值99999");
            return false;
        }
        return true;
    }
    }
}