using System;
using System.Collections.Generic;
using UnityEngine;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// LevelData配置表（自动生成）
    /// </summary>
    [Serializable]
    public class CfgLevelData : BaseConfig
    {
        /// <summary>
        /// 表的主键
        /// </summary>
        [SerializeField]
        public int id { get; set; }

        /// <summary>
        /// 当前的关卡
        /// </summary>
        [SerializeField]
        public int level { get; set; }

        /// <summary>
        /// 这一关卡牌的开始位置X
        /// </summary>
        [SerializeField]
        public float startX { get; set; }

        /// <summary>
        /// 这一关卡牌的开始位置Y
        /// </summary>
        [SerializeField]
        public float startY { get; set; }

        /// <summary>
        /// 这一关两张卡牌X的间距
        /// </summary>
        [SerializeField]
        public float spacingX { get; set; }

        /// <summary>
        /// 这一关两张卡牌Y的间距
        /// </summary>
        [SerializeField]
        public float spacingY { get; set; }

        /// <summary>
        /// 这一关横向放置的数量
        /// </summary>
        [SerializeField]
        public int rowCount { get; set; }

        /// <summary>
        /// 这一关纵向放置的数量
        /// </summary>
        [SerializeField]
        public int colCount { get; set; }

        /// <summary>
        /// 这一关的卡牌总数，就是行*列
        /// </summary>
        [SerializeField]
        public int cardCount { get; set; }

        /// <summary>
        /// 卡牌的长度
        /// </summary>
        [SerializeField]
        public float cardWidth { get; set; }

        /// <summary>
        /// 卡牌的宽度
        /// </summary>
        [SerializeField]
        public float cardHeight { get; set; }

        /// <summary>
        /// 主键（id）
        /// </summary>
        public override object PrimaryKey => id;

    /// <summary>
    /// 数据合法性校验（适配Unity）
    /// </summary>
    public override bool Validate()
    {
        // 主键校验
        if (id <= 0)
        {
            ConfigHelper.LogError("CfgLevelData", $"主键id非法：{id}");
            return false;
        }
        // 表的主键范围校验
        if (id < 1)
        {
            ConfigHelper.LogError("CfgLevelData", $"表的主键id值{id}小于最小值1");
            return false;
        }
        if (id > 99999)
        {
            ConfigHelper.LogError("CfgLevelData", $"表的主键id值{id}大于最大值99999");
            return false;
        }
        return true;
    }
    }
}