using System;
using System.Collections.Generic;
using UnityEngine;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// ResData配置表（自动生成）
    /// </summary>
    [Serializable]
    public class CfgResData : BaseConfig
    {
        /// <summary>
        /// 表的主键
        /// </summary>
        [SerializeField]
        public int id { get; set; }

        /// <summary>
        /// 资源名字
        /// </summary>
        [SerializeField]
        public string resName { get; set; }

        /// <summary>
        /// 资源描述
        /// </summary>
        [SerializeField]
        public string resDes { get; set; }

        /// <summary>
        /// 资源类型
        /// </summary>
        [SerializeField]
        public E_ResType resType { get; set; }

        /// <summary>
        /// 资源的resources方式加载路径的path，相对于Resource/
        /// </summary>
        [SerializeField]
        public string resPath { get; set; }

        /// <summary>
        /// 资源的Editor方式加载路径的path，相对于Assets
        /// </summary>
        [SerializeField]
        public string resEditorPath { get; set; }

        /// <summary>
        /// 资源的AB方式的包名
        /// </summary>
        [SerializeField]
        public string resABPath { get; set; }

        /// <summary>
        /// 主键（id）
        /// </summary>
        public override object PrimaryKey => id;

    /// <summary>
    /// 数据合法性校验（适配Unity）
    /// </summary>
    public override bool Validate()
    {
        // 主键校验
        if (id <= 0)
        {
            ConfigHelper.LogError("CfgResData", $"主键id非法：{id}");
            return false;
        }
        // 表的主键范围校验
        if (id < 1)
        {
            ConfigHelper.LogError("CfgResData", $"表的主键id值{id}小于最小值1");
            return false;
        }
        if (id > 99999)
        {
            ConfigHelper.LogError("CfgResData", $"表的主键id值{id}大于最大值99999");
            return false;
        }
        return true;
    }
    }
}