using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 资源类型
    /// </summary>
    [System.Serializable]
    public enum E_ResType
    {
        /// <summary>
        /// 预制体
        /// </summary>
        Prefabs = 0,
        /// <summary>
        /// 音频
        /// </summary>
        Audio = 1,
        /// <summary>
        /// 视频
        /// </summary>
        Video = 2,
        /// <summary>
        /// 文本
        /// </summary>
        Text = 3,
        /// <summary>
        /// 材质
        /// </summary>
        Materials = 4,
        /// <summary>
        /// 纹理
        /// </summary>
        Texture = 5,
        /// <summary>
        /// 精灵图片
        /// </summary>
        Sprite = 6,
        /// <summary>
        /// 图集
        /// </summary>
        SpriteAtlas = 7,
        /// <summary>
        /// ScriptableObject
        /// </summary>
        SO = 9,
    }
}