using System;
using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class GameManager : BaseManager<GameManager>
{
    public LevelData levelData;
    // 现在的实现方式用不到这个字段
    // private List<Sprite> sprites;
    private List<Material> materials;
    /// <summary>
    /// 当前的关卡
    /// </summary>
    private int curLevel = 1;
    /// <summary>
    /// 当前关卡的牌组
    /// </summary>
    public List<CardData> cardDatas = new List<CardData>();

    private GameManager()
    {
        // levelData = new LevelData();
        // 初始化配置管理器
        ConfigManager.Instance.SetJsonRootPath(ConfigPathType.StreamingAssets, "Config");
        ConfigManager.Instance.SetLoadMode(ConfigLoadMode.PreloadAll);

        // 从清单自动加载所有表（无需指定表名）
        MonoMgr.Instance.StartCoroutine(InitConfigFromManifest());

        Material[] materials = ResMgr.Instance.LoadAll<Material>("Materials");
        this.materials = new List<Material>(materials);

    }

    private IEnumerator InitConfigFromManifest()
    {
        // 核心：仅需加载清单，自动加载所有表
        yield return ConfigManager.Instance.InitFromManifest();

        // 任意查询配置（无需关心表是否手动加载）
        var levelData = ConfigManager.Instance.GetData<CfgLevelData>(1001);

        Debug.Log($"关卡行数：{levelData?.rowCount}");

        // 打印所有表信息
        var manifest = ConfigManager.Instance.GetConfigManifest();
        foreach (var tableMeta in manifest.tables)
        {
            Debug.Log($"表名：{tableMeta.table_name}，数据行数：{tableMeta.row_count}");
        }
    }

    public void Init()
    {
        //构建当前关卡的数据
        //构建当前关卡的牌组,2个一组
        // SingleLevelData levelData = this.levelData.GetLevelData(curLevel);
        // int index = 0;
        // for (int i = 0; i < levelData.rowCount; i++)
        // {
        //     for (int j = 0; j < levelData.colCount; j++)
        //     {
        //         index = i * levelData.colCount + j;
        //         int id = index / 2;
        //         Material material = materials[index / 2];
        //         float x = levelData.startX + j * levelData.cardWidth + j * levelData.spacingX;
        //         float y = levelData.startY - i * levelData.cardHeight - i * levelData.spacingY;
        //         cardDatas.Add(new CardData(material, id, x, y));
        //     }
        // }
        // Debug.Log("GameManager Init");
    }

    internal void GoToNextLevel()
    {
        cardDatas.Clear();
        curLevel++;
        Init();
    }
}
