using System;
using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.Data;
using UnityEngine;


public class GameManager : BaseManager<GameManager>
{
    public CfgLevelData levelData;
    // 现在的实现方式用不到这个字段
    // private List<Sprite> sprites;
    private List<Material> materials = new();
    /// <summary>
    /// 当前的关卡
    /// </summary>
    private int curLevel = 1;
    /// <summary>
    /// 当前关卡的牌组
    /// </summary>
    public List<CardData> cardDatas = new List<CardData>();
    /// <summary>
    /// 初始化游戏逻辑执行需要等待资源加载完毕
    /// </summary>
    private Coroutine initCoroutine;

    private GameManager()
    {
        // levelData = new LevelData();
        // 初始化配置管理器
        ConfigManager.Instance.SetJsonRootPath(ConfigPathType.StreamingAssets, "Config");
        ConfigManager.Instance.SetLoadMode(ConfigLoadMode.PreloadAll);


        // 初始化同步加载所有的表
        ConfigManager.Instance.InitSyncFromManifest();
        //等表加载完成后 初始化资源配置管理器
        ResConfigManager.Instance.Init();

        // 从清单自动加载所有表（无需指定表名）
        // initCoroutine = MonoMgr.Instance.StartCoroutine(InitConfigFromManifest());

        for(int i = 10001;i<=10006;++i)
        {
            ResLoadMgr.Instance.LoadRes<Material>(i,(res)=>
            {
                materials.Add(res);
            },true);
        }

    }

    private IEnumerator InitConfigFromManifest()
    {
        // 核心：仅需加载清单，自动加载所有表
        yield return ConfigManager.Instance.InitFromManifestCoroutine();
        
    }

    public void Init()
    {
        //构建当前关卡的数据
        // 构建当前关卡的牌组,2个一组
        this.levelData = ConfigManager.Instance.GetData<CfgLevelData>(curLevel);
        //设置相机的size
        Camera.main.orthographicSize = levelData.camSize;
        int index = 0;
        for (int i = 0; i < levelData.rowCount; i++)
        {
            for (int j = 0; j < levelData.colCount; j++)
            {
                index = i * levelData.colCount + j;
                int id = index / 2;
                Material material = materials[index / 2];
                float x = levelData.startX + j * levelData.cardWidth + j * levelData.spacingX;
                float y = levelData.startY - i * levelData.cardHeight - i * levelData.spacingY;
                cardDatas.Add(new CardData(material, id, x, y));
            }
        }
        Debug.Log("GameManager Init");
    }

    internal void GoToNextLevel()
    {
        cardDatas.Clear();
        curLevel++;
        if(curLevel>ConfigManager.Instance.GetTable<CfgLevelData>().Count)
        {
            curLevel = 1;
        }
        Init();
    }
}
